name: 📦 Build npm Package
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout source code
        uses: actions/checkout@v4

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@kaoto'
          cache: 'yarn'

      - name: ☕ Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      
      - name: Install dependencies
        run: yarn

      - name: 📦 Build the catalog
        run: yarn build

      - name: 💅 Run eslint
        run: yarn workspaces foreach --verbose --all --topological-dev run lint

      - name: 🔍 Check for uncommitted catalog changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "❌ Uncommitted changes detected after building the catalog."
            echo ""
            echo "🔧 It looks like the catalog generator has been modified, but the generated files in the 'catalog/' folder were not committed."
            echo ""
            echo "✅ To fix this:"
            echo "   1. Run 'yarn build' (this builds the catalog and copies it to the root 'catalog/' folder)."
            echo "   2. Commit the updated files using:"
            echo "      git add catalog && git commit -m \"Update generated catalog\""
            echo ""
            echo "🔁 This ensures that the repository always reflects the current state of the generator."
            echo ""
            git status
            exit 1
          else
            echo "✅ Catalog is up-to-date."
          fi

      - name: 📤 Upload artifacts for publish (only on main)
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: built-catalog
          path: |
            packages/camel-catalog/dist/
            catalog/
