name: 📦 Build npm Package
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout source code
        uses: actions/checkout@v4

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@kaoto'
          cache: 'yarn'

      - name: ☕ Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      
      - name: Install dependencies
        run: yarn

      - name: 📦 Build the catalog
        run: yarn build

      - name: 💅 Run eslint
        run: yarn workspaces foreach --verbose --all --topological-dev run lint

      - name: 🔍 Compare generated catalog with committed version
        run: |
          DIST_DIR="packages/camel-catalog/dist/camel-catalog"
          COMMITTED_DIR="catalog"

          echo "🔍 Comparing $DIST_DIR with $COMMITTED_DIR..."

          # Check for content differences
          if ! diff -rq "$DIST_DIR" "$COMMITTED_DIR" > /dev/null; then
            echo "❌ Catalog content differs from committed version!"
            echo ""
            echo "🔧 Run 'yarn build' locally and commit the updated catalog files."
            echo ""
            echo "💡 This check compares the actual content of the files, ignoring filename hashes or timestamps."
            echo ""
            echo "--- Changed files:"
            diff -rq "$DIST_DIR" "$COMMITTED_DIR" || true
            exit 1
          else
            echo "✅ Generated catalog matches committed files."
          fi
