name: 🚀 Publish npm Package

on:
  workflow_run:
    workflows: [ "📦 Build npm Package" ]
    types:
      - completed

jobs:
  publish:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'

    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout source code
        uses: actions/checkout@v4

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@kaoto'
          cache: 'yarn'

      - name: 📦 Install deps & build
        run: |
          yarn

      - name: 📥 Download built catalog
        uses: actions/download-artifact@v4
        with:
          name: built-catalog

      - name: 🚀 Publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.KAOTO_NPM_TOKEN }}
        run: yarn publish